package application;

import java.io.IOException;
import javafx.fxml.FXML;
import javafx.stage.Stage;
import javafx.event.ActionEvent;

public class LoginPageController {

	// Event Listener on Button.onAction
	@FXML
	public void btnLogin(ActionEvent event) {
		// TODO Autogenerated
	}
}
